<script setup lang="ts">
import { computed } from "vue";
import type { SessionDetailData } from "@lw-aiusage/application";
import { totalTokens } from "@lw-aiusage/core";
import { formatTokenDetail } from "../format";
import { useI18n } from "../i18n";
const props = defineProps<{ detail: SessionDetailData }>();
const emit = defineEmits<{ close: []; viewUsage: [] }>();
const { t, locale } = useI18n();
const maxPointTokens = computed(() => Math.max(...props.detail.timeline.map((item) => item.totalTokens), 1));
</script>
<template>
  <div class="drawer-backdrop" @click.self="emit('close')"><aside class="detail-drawer session-drawer"><div class="drawer-heading"><div><p class="eyebrow">{{ t("sessions.detailEyebrow") }}</p><h2>{{ detail.summary.sessionId }}</h2></div><button class="drawer-close" @click="emit('close')">×</button></div><div class="drawer-summary"><span class="source-badge">{{ detail.summary.source }}</span><span>{{ detail.summary.primaryModel }}</span><span>{{ detail.summary.recordCount }} {{ t("usage.recordsCount") }}</span></div><div class="session-kpis"><div><span>{{ t("sessions.started") }}</span><strong>{{ new Date(detail.summary.startedAt).toLocaleString(locale === "zh" ? "zh-CN" : "en-US") }}</strong></div><div><span>{{ t("sessions.lastActive") }}</span><strong>{{ new Date(detail.summary.lastActiveAt).toLocaleString(locale === "zh" ? "zh-CN" : "en-US") }}</strong></div><div><span>{{ t("sessions.span") }}</span><strong>{{ Math.round(detail.summary.spanMs / 60000) }} min</strong></div><div><span>{{ t("usage.total") }}</span><strong>{{ formatTokenDetail(detail.summary.totalTokens, locale) }}</strong></div><div><span>{{ t("sessions.cost") }}</span><strong>${{ detail.summary.estimatedCostUsd.toFixed(4) }}</strong></div><div><span>{{ t("sessions.cachedShare") }}</span><strong>{{ detail.summary.cachedInputShare === undefined ? "—" : `${(detail.summary.cachedInputShare * 100).toFixed(1)}%` }}</strong></div><div><span>{{ t("sessions.projects") }}</span><strong>{{ detail.summary.projects.join(", ") }}</strong></div><div><span>{{ t("sessions.models") }}</span><strong>{{ detail.summary.models.join(", ") }}</strong></div></div><h3>{{ t("sessions.timeline") }}</h3><div class="session-timeline"><div v-for="point in detail.timeline" :key="point.start" class="timeline-row"><time>{{ new Date(point.start).toLocaleTimeString(locale === "zh" ? "zh-CN" : "en-US", { hour: "2-digit", minute: "2-digit" }) }}</time><div class="timeline-track"><span :style="{ width: `${Math.max(4, point.totalTokens / maxPointTokens * 100)}%` }"></span></div><strong>{{ formatTokenDetail(totalTokens(point.usage), locale) }}</strong></div></div><button class="secondary-action drawer-session-action" @click="emit('viewUsage')">{{ t("sessions.viewRecords") }}</button></aside></div>
</template>
